[package]
name = "lindera-unidic-builder"
version = "0.2.0"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>"
    ]
edition = "2018"
description = "A Japanese morphological dictionary builder for UniDic."
documentation = "https://docs.rs/lindera-unidic-builder"
homepage = "https://github.com/bayard-search/lindera-unidic-builder"
repository = "https://github.com/bayard-search/lindera-unidic-builder"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "builder", "unidic"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.2"
clap = "2.33.0"
encoding = "0.2.33"
lindera-core = "0.2.0"
tantivy-fst = "0.2.1"

[[bin]]
name = "lindera-unidic"
path = "src/main.rs"
